---
# defaults file for ansiblered-deck-ansible

workshop_image: images/ansible-logo.png
workshop_name: Ansible Essentials Workshop
workshop_presenter: '&nbsp;'
workshop_title: '&nbsp;'
workshop_message: '&nbsp;'

